### ISSUE TITLE
Add option to allow insecure https  (--allow-insecure)

### ISSUE THREAD

**Issue by ant31** [app-registry/appr#42]

**Comment by ecordell** [comment]
The idea is to support custom CA certs for a registry.  

By default, requests won't load system certs, which means there's no way to tell appr to trust other certs without using the `REQUESTS_CA_BUNDLE` env var.

It might make sense to add an `--extra_ca_certs` flag, or have a appr specific `APPR_CA_BUNDLE` env var, or both.
