### ISSUE TITLE
helm install options are not supported

### ISSUE THREAD

**Issue by joejulian** [app-registry/appr#43]
`helm registry install quay.io/samsung_cnct/ingress-nginx@0.1.5-0 --name ingress-nginx --namespace default --values /home/jjulian/.kraken/jjregistry/quay.io-ingress-nginx.helmvalues` fails:

```
usage: appr [-h]
            {show,inspect,logout,plugins,helm,pull,list,delete-package,version,push,login,config,channel}
            ...
appr: error: unrecognized arguments: --name ingress-nginx --namespace default --values /home/jjulian/.kraken/jjregistry/quay.io-ingress-nginx.helmvalues

E0706 23:09:02.730713   16604 portforward.go:209] Unable to create listener: Error listen tcp6 [::1]:41323: bind: cannot assign requested address
Error: This command needs 1 argument: chart name
Error: plugin "registry" exited with error
```

In https://github.com/app-registry/appr/blob/master/appr/commands/plugins/helm/cnr.sh, the switches are all passed to `appr pull`. Unsupported switches should probably be silently ignored.

Further, the needed switches are not passed to `helm install` preventing it from being assigned the expected name or being installed into the correct namespace.

**Comment by ant31** [comment]
note: this code shoud be  deleted this code (plugins/*)
Can you try to reinstall the plugin from https://github.com/app-registry/appr-helm-plugin 

Also all unknown should be passed to helm install, but there was a bug. 
Still all options are passed to helm install after -- separator: 

```
# helm registry install [appr-opts] -- [helm-opts]
helm registry install quay.io/samsung_cnct/ingress-nginx@0.1.5-0 -- --name ingress-nginx --namespace default
```

let me know if it's working for you

**Comment by joejulian** [comment]
Ah, ok. I'll pull the shell script and the plugin.yaml from there. I still can't install that way, of course, because of the dynamic bindings.

**Comment by ant31** [comment]
that's 2 separate issues. 
1. The installation process isn't practical / working inside alpine
2. Can't pass options to helm install

for 1, do you have a dockerfile I can play, with ?

**Comment by joejulian** [comment]
https://github.com/samsung-cnct/k2-tools/blob/master/Dockerfile

**Comment by ant31** [comment]
@joejulian 

About this current issue, it seems fixed and working with the version >=5.1
unknow arguments are sent to Helm. 
I would prefer to keep the cli failing for other cases (regarding your PR). 
Can you confirm ? 

About the installation process, I've published a command: 
```
appr plugins install helm
```
that install the `.helm/plugins/registry` files and creates a symlink to the appr script. 
In a Dockerfile, once appr is installed, we can call this command to get the registry plugin correctly setup.

**Comment by joejulian** [comment]
Excellent. This looks like it should work for our needs. I'll test this shortly.

**Comment by joejulian** [comment]
Works for me. Thanks.
