### ISSUE TITLE
Add option to support self-signed certificate

### ISSUE THREAD

**Issue by sbueringer** [app-registry/appr#55]
Hi,

it would be nice if appr could provide an option to specify a custom keystore / bundle, so that it can be used with registries with self-signed certificates.

I tried to set the environment variable [APPR_CA_BUNDLES](https://github.com/app-registry/appr/blob/master/appr/client.py#L32-L36) to a folder with our CA pem file and to the CA file, which should be trusted, itself, e.g.:
````
export APPR_CA_BUNDLES=/tmp/certs/
# or
export APPR_CA_BUNDLES=/tmp/certs/Root-CA.pem
````
If i understand the documentation of [requests](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) correctly, this should work. But we only got:
````
Api-version: .. Connection error
Client-version: 0.6.1
````
I can only guess that the environment variable is not used correctly?

**Comment by ant31** [comment]
Hi, thanks for report, 
can you provide the command line used ? 

also could you try the options: 
```
  -k, --insecure        turn off verification of the https certificate
  --cacert [CACERT]     CA certificate to verify peer against (SSL)
```

-k should skip certs verification, --cacert should have the same effect than setting APPR_CA_BUNDLES

**Comment by sbueringer** [comment]
Thanks for the fast response. Actually -k and --cacert work.

I guess part of the problem was I first used version 0.6.1 and the change which added -k and --cacert was after the 0.6.1 release. 

I've build the appr binary myself with the current version and now both options work.
