### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by sbueringer** [app-registry/appr#56]
Hi,

currently appr and accordingly the helm app registry plugin is only supported on Linux and OSX. Would it be possible to support it also on Windows?

As far as I'm aware there biggest problem is that the appr binary is build with travis ci (I didn"t look in detail at the GitLab build) and pyinstaller. Travis ci only builds on Linux and OSX and pyinstaller doesn't support cross-compilation. But I saw there is one release of [appr-helm-plugin](https://github.com/app-registry/appr-helm-plugin/releases) with a Windows binary.

We got it running on Windows by building the appr.exe locally and creating a Powershell version of [cnr.sh](https://github.com/app-registry/appr-helm-plugin/blob/master/cnr.sh).

Is there a solution for the cross-compilation problem?

**Comment by ant31** [comment]
The binary is already compiled for windows with appyvor, but looks like it didn't not trigger latest releases). 

What we weere missing is the powershell script.

**Comment by ant31** [comment]
Could you submit your Powershell script ?

**Comment by sbueringer** [comment]
We've implemented parts of the script to get it to work on our machines. Unfortunately we skipped the "download"part. But we'll add this very soon (today or tomorrow) and I'll post the whole script. For now, that's the part that just invokes the appr.exe

````
function Appr_Helm($helm_args){
    Invoke-Expression "$Env:HELM_PLUGIN_DIR/appr.exe $helm_args --media-type=helm"
}

if(!(Test-Path $Env:HELM_PLUGIN_DIR)){
    $Env:HELM_PLUGIN_DIR="$Env:HOME/.helm/plugins/registry"
}

switch ($args[0]) {
    "install" { Invoke-Expression "$Env:HELM_PLUGIN_DIR/appr.exe helm install $args" }
    "upgrade" { Invoke-Expression "$Env:HELM_PLUGIN_DIR/appr.exe helm dep $args" }
    "dep"     { Invoke-Expression "$Env:HELM_PLUGIN_DIR/appr.exe helm dep $args" }
    "pull"    { Invoke-Expression "$Env:HELM_PLUGIN_DIR/appr.exe pull --media-type helm $args" }
    { @("push", "list", "show", "delete-package", "inspect") -contains $_ } { Appr_Helm $args }
    default { Invoke-Expression "$Env:HELM_PLUGIN_DIR/appr.exe $args"}
}

````

**Comment by ant31** [comment]
@sbueringer would you be able to help me building the branch `client_deploy` on windows ? 
It has c dependency (to compile) and I keep failing to find the configuration for build it on https://www.appveyor.com/

**Comment by sbueringer** [comment]
@ant31 I'll try later today

**Comment by sbueringer** [comment]
@ant31. I didn't got it to work. 

I tried it directly on Windows [.appveyor.yaml](https://github.com/sbueringer/appr/blob/fix_windows_build/.appveyor.yml) and in Cygwin [.appveyor.cygwin.yaml](https://github.com/sbueringer/appr/blob/fix_windows_build/.appveyor.cygwin.yml). In both cases it came down to compilation errors in jsonnet [log](https://ci.appveyor.com/project/sbueringer/appr/build/1.0.79). 

Maybe it's related to this [issue](https://github.com/google/jsonnet/issues/300) in jsonnet.

**Comment by ant31** [comment]
@sbueringer yes it's related to jsonnet, I'm working on it. 
I removed this dependency for the windows build for now.

**Comment by ant31** [comment]
@sbueringer Are you still using Appr? if yes, I've released a 'windows' build in https://github.com/app-registry/appr-helm-plugin/releases/tag/v0.7.0, using your powershell script (with few modifications to reflect latest changes). 

Would you be able to validate that is working ?

**Comment by sbueringer** [comment]
@ant31 
I tested the script, made some fixes and it now works (at least on my machine :)).  I've opened an PR (https://github.com/app-registry/appr-helm-plugin/pull/43). 

The packaged release should also be verified again, as I just checked out the repository, changed the plugin.yaml and fixed the .ps1 script.

**Comment by sbueringer** [comment]
@ant31 Could you please create a new release (of appr-helm-plugin) with the merged branch. This would make it easier for me to recommend the usage of the appr-helm-plugin on Windows to my colleagues :)
