### ISSUE TITLE
helm registry install doesn't propagate errors from Kubernetes

### ISSUE THREAD

**Issue by jeff-knurek** [app-registry/appr#81]
When running:
`helm registry install quay.io/myorg/chartname --name releaseName --namespace prod -f env-values-overrides/prod.yaml`
If there was an error _(for example: in the env-values-overrides/prod.yaml file an environment variable has a value but no name)_ and Kubernetes fails to deploy, there will be an error logged:

`Error: release releaseName failed: Deployment.apps "prod-appName" is invalid: spec.template.spec.containers[0].env[3].name: Required value`

But `helm registry` exists with a 0 (aka: false success)

----
if not using the plugin, `helm` errors with status 1

----
same problem exists for `helm registry upgrade --install`

**Comment by ant31** [comment]
what's is your client version ? this should have been fixed

**Comment by jeff-knurek** [comment]
yup, upgraded to `0.7.3` and it's resolved

(was using the previous version of this docker image which I guess had `v0.5.0`: https://github.com/samsung-cnct/docker-helm-registry-agent )
